# Numpy tasks

## General

In [1]:
import numpy as np

### Task Version number
> a) extract numpy version number

## Arrays

---



### Task: Speed comparison, numpy is faster

> a) compute the sum of squared values from 10-10 000 using a list comprehension. This corresponds to:
$$
\sum_{i=10}^{10 000}i^2
$$

> b) compute the same using numpy

> c) perform a speed comparison between the two approaches  *Hint* you can measure time using:
```
import time
start = time.time()
# your code
time_taken = time.time() - start
```

### Task: Speed comparison, no lists are faster

1) create a for loop where you append numbers to a list and a numpy array (let's say 1 000 000). Show that list are faster than numpy arrays in this situation.

This is a design decision which makes python cheap to append to (read more [here](https://stackoverflow.com/questions/5932328/internals-of-python-list-access-and-resizing-runtimes)).

**Bonus**: You can make numpy noticably faster by preallocating memory. E.g. by creating an array of zeros and assigning the values instead of appending them.


## Creating and combining arrays

---

### Task: Combining arrays

stack  two  numpy arrays vertically.

**Example:**

```python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Output:
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

## Indexing arrays

---

### Task: Extract the middle
> extract the middle row in an 1D array. If there is an even amount of arrays extract the two middle rows.

**Example:**
```
d = np.array([1, 2, 3])
print(get_middle(d))
print(get_middle(np.arange(4)))
```

Output
```
2
[1 2]
```



### Task: Word frequencies
> a) Given one array (of strings) select all values in a corresponding  array that corresponds to the highest values in the initial array.

**Example:** Most frequent words
```
words = np.array(["a", "duck", "dog", "the"])
counts = np.array([30, 2, 4, 110])
print(f(words, counts))
```

Output
```
"the"
```

> bonus: generalize it to the n highest values

## Formula to Code

---

### Task: The Euclidian Norm
> implement the euclidian ($L^2$) norm defined as: 

$$||x||_2 = \sqrt{x^2_1 + x^2_2 + ... x^2_n}$$

Check that it it gives the same result as `np.linalg.norm`

### Task: The sigmoid function
The sigmoid (or the logistic) function is a function which is normalized between 0 and 1. It is defined as:
$$
s(x) = \frac{1}{1+e^{-x}}
$$

> Implement the sigmoid function

Example:
```
print(s(0))
print(s(2))
print(s(100))
```

Output:
```
0.5
0.88079...
1.0
```

> **Bonus:** plot the function

### Task: Vector Distances
> Implement the following distances:
- Euclidian ($L^2$) distance
- Cosine distance
- the Hamming distance


**The euclidian distance** is a distance measure which denoted the length between two vectors $a$ and $b$ as defined by:
$$
dist(a, b) = || a-b || 
$$

You can check that it give the same result as `scipy.spatial.distance.euclidean`.

**The cosine distance** is a distance measure based on the angle between to vectors, $a$ and $b$. It can be shown that it is equal to: 

$$
dist(a, b) = 1 - cos(\theta) =  1 - \frac{a \cdot b} {|| a || \cdot || b ||}
$$

You can check that it give the same result as `scipy.spatial.distance.cosine`.


**The Hamming distance** between 1-D arrays $u$ and $v$, is simply the proportion of disagreeing components in $u$ and $v$. 

**Example**:
```python
u = [2, 6, 5, 8, 1, 2, 4, 5, 2, 6]
v = [0, 0, 5, 8, 1, 2, 4, 5, 2, 6]
print(hamming(u, v))
```

Output:
```
0.2
```

You can check that it give the same result as `scipy.spatial.distance.hamming`.


> **Bonus**: Cosine similarity is a similarity measure which is defined as $1 - cos\_dist$. Why does this constitute a reasonable measure of similarity? *Hint* What is the potential range of values. Try out a few vectors and see.

<br /> 

<details>
  <summary>Answer</summary>

  Cosine similarity is normalized. That means that if the vector are the same (ignore length/magnitude) the cosine similarity is 1 (i.e. they as similar as can be). So the closer it is to 1 the more similar the vectors are.
</details>

<br /> 


> **Bonus**: Why would you want to use cosine distance instead of the euclidian norm?

<br /> 

<details>
  <summary>Answer</summary>

  Cosine distance, or cosine similarity, is typically used to denote the distance between two vectors ignoring magnitude. Actually it can be [shown](https://stats.stackexchange.com/questions/146221/is-cosine-similarity-identical-to-l2-normalized-euclidean-distance) that euclidian norm of a normalized vector is proportional to the cosine distance.
</details>

<br /> 


### Task: Shannon Enthropy

Calculate the shannon entropy of the follow dice throws:
```
[1, 2, 3, 4, 5, 6]
[1, 2, 1, 3, 1, 4]
[6, 5, 5, 6, 5, 4]
```
Both given a standard dice probability $\frac{1}{6}$ for each outcome and  weighted dice with the probabilites:

`{1: 0.1, 2: 0.1, 3: 0.1, 4: 0.2, 5: 0.2, 6: 0.3}`

Shannon entropy is defined as:

$$
entropy(x) := \sum_{i=1}^n P(x_i) \cdot log P(x_i)
$$


### Task Finding the minimum of a parabola

> 1) program a function that given a list of grid $x$ and a tuple with three entries ($b_1$, $b_2$, $b_3$) computes the parabola $b_1 + b_2x + b_3x^2$ 

```python
x = np.arange(-10, 10, 0.1)
y = f(x, betas=(1, 1.4, 2)) 
```

Which corresponds to $1 + 1.4x + 2x^2$.

> 2) Program a function which calculates the gradient $f'(x_i)$ using derivatives.

<br /> 

<details>
  <summary>Help with derivatives</summary>

---

To solve the task it might be convenient to know:
- The derivative of a constant is 0 

$\frac{d}{dx} c = 0$

- The derivative of $c \cdot x$ is $c$

$\frac{d}{dx} cx = c$

- The derivative of $x^n$ is $n \cdot x^{n-1}$

$\frac{d}{dx} x^n = n \cdot x^{n-1}$

---

</details>


For example:
```python
x = 2
gradient = df(x, betas=(1, 1.4, 2))
print(gradient)
```

Output:
```
9.4
```
> 3) Using 2) create a function which given an initial starting state i) computes gradient ii) minimizes the gradient by taking a small step (learning rate) toward the minimum iii) keep doing this `n` times

Test that you function get similar results as you would get using provided `n` is high enough and a reasonable learning rate:
```
x[y.argmin()]  # which value of x corresponds to the minimum of y
```

**Bonus**: Instead of setting an `n` make it so that the functions stops when there only little 

### Task: Ordinary Least Squares

Ordinary least squares (OLS) is a popular apprach for estimating a linear fit. Its matrix formulation is given by:

$$
(X^TX)\hat{\beta}=X^Ty
\Rightarrow
\hat{\beta}=(X^TX)^{-1}X^Ty
$$

> Calculate the OLS of the given datapoints below.

Feel free to check your results using `lm()` in R or using [`statsmodels`](https://www.statsmodels.org/stable/regression.html) or [`sklearn`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

**Bonus:** Plot the fit, does it make sense?

**Bonus:** Using OLS fit a quadratic polynomial

**Bonus:** lm() in python. R has a convenient function `lm` where you fit a function using a string formula and dataset. Create a similar function in python by parsing the string. This would look something like this: 
```
data = {"x": np.array([0, 1, 2, 3]), "y": np.array([-1, 0.2, 0.9, 2.1]) }
lm(formula="y~1 + x", data=data)
```

In [ ]:
# our x, y datapoints
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])

# add a list of ones denoting intercept
X = np.vstack([np.ones(len(x)), x]).T
print(X)
print(y)

# solve using OLS:
# ...

### Task: One-hot encoding

One-hot encoding denote transforming a series of categories (e.g. "Natural language processing", "Neuroscience" ... or 1, 2, ...) into a matrix of shape (*, num_classes) that have zeros 
everywhere except where the index (of the last dimension) mathces the corresponding value of the input label, in which case it will be 1. For instance the vector `[0, 1, 0]` could denote "Neuroscience".

**Example:**
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr)
print(one_hot(arr))

```

Output:
```
array([2, 3, 2, 2, 2, 1])
array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])
```

# Additional Task

---


## Creating Array

### Task: Creating the bullseye

> Create a function which for an input shape (Tuple[int, int]) return a matrix of the same shape where the border are ones, the middle is 8 and the remainder is zeros.

**Example:**
```
print(bullseye((5, 5)))
print(bullseye((5, 6)))
```

Output:
```
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 9. 9. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

```