# Formulas and Linear algebra

When using programming for scientific computing it is important to be able to translate
between mathematical notation and programming. This is what today's segment will try
to teach you. 

Today we will be using `numpy`, a python package for numerical computation most notably
implementing n-dimensional arrays (also called matrices, vectors and tensors).

You can install `numpy` in the notebook by running:

`
!pip install numpy
`

If you want to install it from the terminal remove the `!`

> If you have done mathematics of similar course, you might find much of this 
notebook trivially simple, feel free to start of with the exercises.

-----

## Numpy and basic linear algebra

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, also called matrices or tensors, and tools for working with these arrays. 

If you are already familiar with `Matlab` or `R`, you might find these tutorials useful:
- [NumPy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
- [NumPy for R users](http://mathesaurus.sourceforge.net/r-numpy.html)

we will start of by loading numpy:

In [1]:
import numpy as np

## Arrays




A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension. A a one dimensional array (shape `(n,)`) corresponds to a vector.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
a = np.array([1, 2, 3])  # Create a rank 1 array

print("a is type: ", type(a))
print("a has shape: ", a.shape)
print(a[0], a[1], a[2])  # indexing
a[0] = 5  # Change an element of the array
print(a)     

a is type:  <class 'numpy.ndarray'>
a has shape:  (3,)
1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array i.e. a matrix
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


## Mathematical operations on Arrays

----


Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [5]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
print(x + y)
# or
# print(np.add(x, y))

[[ 6  8]
 [10 12]]


In [6]:
# Elementwise difference; both produce the array
print(x - y)
# or
# print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]


In [10]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
# Elementwise division; both produce the array
print(x / y)
# or
# print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [7]:
# Elementwise product; both produce the array
print(x * y)
# or 
# print(np.multiply(x, y))

[[ 5 12]
 [21 32]]


**Note**: that unlike other programming languages (e.g. Matlab), `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects (more on this in the next section)

In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; all produce 219
print(v @ w)
# or equivalent:
# print(v.dot(w))
# print(np.dot(v, w))

219
219
219


## List and Sums

A notation which often seems daunting is the summation notation (unjustifiably so):

$$
\sum_{i=1}^{11} i + 4
$$

What this mean is that for each number from 1 to 11:
- take the number, 
- add 4 to it
- sum them all together

```python
numbers_to_sum = []
for n in range(1, 12): # not including 12
    numbers_to_sum.append(n+4)
sum(numbers_to_sum)

# or written using a list comprehension
# (which almost reads line a sentence)
sum([n + 4 for n in range(1, 12)])
```

We assume you are familiar with python list. The rest of this section will compare numpy
array with python lists.

----

Numpy and list differ in a variety of ways. Speed being one. How to mathemetical operations works being another:

In [16]:
# a list from 0 to 9
np_range = np.arange(10)
py_range = list(range(10))

# Elementwise addition in list
print([t + 2 for t in py_range])

# Elementwise addition in numpy array
print(np_range+2)


[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[ 2  3  4  5  6  7  8  9 10 11]


trying the same thing with lists:

```python
print(py_range + 2)
```

> Q: What will happen, when I run this code?

In [18]:
# trying this with python lists
# py_range + 2

**Speed comparison** is left as an exercise for the reader see `numpy_task.ipynb`.

Why are numpy arrays faster for scientific computing? Well at least, 

1) They use less bytes to represent the number, 
2) keep things in the same place to rather than simply pointing to them. You could
    imagine why this is efficient when dealing with smaller objects, but if you are dealing with large object moving them all to the same place takes time.
3) numpy enforce types which lists does not. This makes list very flexible, but also slow.

## Mutability

A way in which numpy arrays and lists are similar is that they are both mutable. I.e.
you are allowed to change to object without recreating it.

In [23]:
np_range[3] = 0 # replace element with 0
print(np_range)
py_range[6] = 0 
print(py_range)

[1 1 2 0 4 5 6 7 8 9]
[0, 1, 2, 0, 4, 5, 0, 7, 8, 9]


## Matrices and matrix multiplications

---

A matrix is in abstraction to deal with linear systems. For example

$$
2x + 4y + 6z = 18\\

4x + 5y + 6z = 24\\

3x + y + 2z = 4\\
$$

$$
A = \begin{bmatrix}
2 & 4 & 6\\
4 & 5 & 6\\
3 & 1 & 2
\end{bmatrix},

x = \begin{bmatrix}
x \\
y \\
z 
\end{bmatrix},

y = \begin{bmatrix}
18 \\
24 \\
4 
\end{bmatrix}

$$

> Blackboard: Practical example of how to use the abstraction



Thus we would want to implement a complex system of linear equations as

$$
  
    \begin{cases}
      a_{11} \cdot x_1 +  a_{12} \cdot x_2 + \cdots a_{1n} \cdot x_n = y_1  \\
      a_{21} \cdot x_1 +  a_{22} \cdot x_2 + \cdots a_{2n} \cdot x_n = y_2  \\
      \cdots \\
      a_{n1} \cdot x_1 +  a_{n2} \cdot x_2 + \cdots a_{1n} \cdot x_n = y_n  \\
    \end{cases}  
$$

Which gives rise to the quite natural compact notation:

$$
A \cdot x = y
$$

> Q: Where have you seen this notation before?
<!--
Linear regression 
You can write it out to:
a_1 * x_1 + a_2 * x_2 + ... = y
it also translates nicely to neural networks
-->

> Blackboard: Example of multiplication
<!-- For solving linear systems -->


<br /> 

<details>
  <summary>Rules for multiplication</summary>

---

If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix,
$$
A=\begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1n} \\
 a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{m1} & a_{m2} & \cdots & a_{mn} \\
\end{bmatrix},
\quad B=\begin{bmatrix}
 b_{11} & b_{12} & \cdots & b_{1p} \\
 b_{21} & b_{22} & \cdots & b_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{n1} & b_{n2} & \cdots & b_{np} \\
\end{bmatrix}
$$

the *matrix product* (denoted without multiplication signs or dots) is defined to be the $m \times p$ matrix.
$$
\mathbf{C}=\begin{bmatrix}
 c_{11} & c_{12} & \cdots & c_{1p} \\
 c_{21} & c_{22} & \cdots & c_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
 c_{m1} & c_{m2} & \cdots & c_{mp} \\
\end{bmatrix}
$$
such that 
$$c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} +\cdots + a_{in}b_{nj}= \sum_{k=1}^n a_{ik}b_{kj}$$
for $i = 1, ..., m$ and $j = 1, ..., p$.

---

</details>


This has the addded benefit of preserving:

vector addition:
$$
A \cdot (x + y) = A \cdot x + A \cdot y
$$

and scalar multiplication
$$
A \cdot (\alpha \cdot x) = \alpha \cdot A \cdot x 
$$

These properties are quite convenient, but for instance we does loose commutativity (that is $a \cdot b$ does not equal $b \cdot a$). 

> Exercise: Multiply A with x and A with A by hand.

> Exercise: Check the answer using numpy, *Hint* the dot product corresponds to matrix multiplication

In [45]:
# for the exercise

### Working with matrices in numpy
You can do a bunch of things with matrices including getting eigenvalues, determininants and much more. Here I will present a few cases:

In [26]:
arr = np.random.randint(0, 5, size=9)
arr = arr.reshape((3, 3))
print(arr, "\n", "---")

# Transpose
print(arr.T)

[[3 4 0]
 [2 0 0]
 [1 3 4]] 
 ---
[[3 2 1]
 [4 0 3]
 [0 0 4]]


In [65]:

A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
y = np.array([25, -10, -4])
print(A)

# solve for x
x = np.linalg.solve(A, y)
print(x)
# test solution
print(A @ x == y)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[ 5.  3. -2.]
[ True  True  True]


## Creating, combining and indexing arrays


> Self-paced: These following are function for creating, combining and indexing arrays. They are really good to know. Go through them and ask if there is any problems.

### Creating arrays
Numpy also provides many functions to create arrays:



In [14]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [15]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [16]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [17]:
e = np.random.random((2,2)) # Create an array filled with random values (uniform 0-1)
print(e)

[[0.55818153 0.02395433]
 [0.64079631 0.71815421]]


You can also do sampling from distributions, e.g.

In [66]:
e = np.random.normal(1, 1, size = 10) # 10 samples from Normal(1, 1) 
print(e)

[-0.02111395  2.76466364  0.4556717   1.59308923  1.08872265  0.22306349
  1.91825501  2.72253673  0.14311447  1.18108731]


### Combining arrays
You can naturally also combine arrays for example by stacking for concatenating:

In [72]:
v = np.random.random((2,2))
c = np.concatenate([v, v])
print(c.shape)
c = np.stack([v, v])
print(c.shape)

(4, 2)
(2, 2, 2)


### Array indexing


Numpy offers several ways to index into arrays.

#### Slicing

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

**Note for next time teaching**: This section should probably be slightly modified to have a bit more meaningful workflow

In [18]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [19]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [20]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [21]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [22]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:


In [23]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [24]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [25]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[ 1  6  7 11]


In [27]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [28]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [29]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

## Data types

---

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:




In [30]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

# Learning more
---
- 2D matrix calculus (up to a point) can be understood as transformation of a space. This abstraction is nice for building intuition, but as this is mostly introductory I will recommend 3Blue1Brown series on [the essence of linear algebra](https://www.youtube.com/watch?v=XkY2DOUCWMU).

- There is also a free [book](https://data.math.au.dk/interactive/linalg/2020/index.html) from Aarhus university on matrix algebra which you might find useful as it includes videos and exercises as well). It is sadly in Danish.

- If you wish to is recap on this later there is a wonderfully [brief overview of numpy](https://www.youtube.com/watch?v=19u7w2HdkBE) på Gert at Aarhus university, sadly also Danish. If you prefer english there is a [1 hour introduction to numpy](https://www.youtube.com/watch?v=QUT1VHiLmmI&t=2686s) on code camp's youtube channel. I also recommend the other videoes by Gert on his channel.